language: en
# pipeline:
  # - name: WhitespaceTokenizer
  # - name: RegexFeaturizer
  # - name: CRFEntityExtractor
  # - name: EntitySynonymMapper
  # - name: LexicalSyntacticFeaturizer
  # - name: CountVectorsFeaturizer
  #   analyzer: "word"
  #   OOV_token: oov
  # - name: CountVectorsFeaturizer
  #   analyzer: "word"
  #   OOV_token: oov
    # analyzer: "char_wb"
    # min_ngram: 1
    # max_ngram: 4
  # - name: EntitySynonymMapper
  # - name: DIETClassifier
  #   epochs: 200
  #   constrain_similarities: True
  #   model_confidence: linear_norm
  # - name: EntitySynonymMapper
  # - name: ResponseSelector
  #   epochs: 200
    # constrain_similarities: True
    # model_confidence: linear_norm
   # - name: FallbackClassifier
   #   threshold: 0.6

### Transformers####
pipeline:
  - name: HFTransformersNLP
    model_name: "bert"
    model_weights: "bert-base-uncased"
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: CRFEntityExtractor
  # - name: Countvecorfeaturize
  - name: DIETClassifier
    # constrain_similarities: True
    # model_confidence: linear_norm
    epochs: 200
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
    # constrain_similarities: True
    # model_confidence: linear_norm
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.2


### ConveRTTokenizer + ConveRTFeaturizer####
# pipeline:
#   - name: ConveRTTokenizer
#     "intent_tokenization_flag": False
#     "intent_split_symbol": " "
#     "token_pattern": None
#     "model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
#   - name: ConveRTFeaturizer
#     "model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
#   - name: CRFEntityExtractor
#   - name: EntitySynonymMapper
#   - name: DIETClassifier
#     epochs: 200
#     constrain_similarities: True
#     model_confidence: linear_norm
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 200
#     constrain_similarities: True
#     model_confidence: linear_norm

# pipeline: 
# """320 version"""
# """This version is ver similar to the one above, but some enhancement is seen with random talk (lower confidence).countvecorfeaturize is not so good..."""
#   - name: ConveRTTokenizer
#     "intent_tokenization_flag": False
#     "intent_split_symbol": " "
#     "token_pattern": None
#     "model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
#   - name: ConveRTFeaturizer
#     "model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
#   - name: RegexFeaturizer
#   - name: CRFEntityExtractor
#   - name: DIETClassifier
#     epochs: 200
#     constrain_similarities: True
#     model_confidence: linear_norm
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 200
#     constrain_similarities: True
#     model_confidence: linear_norm



### Spacy###

# pipeline:
#"""508 -- 747 version"""
  # - name: SpacyNLP
  #   model: en_core_web_md
  # - name: SpacyTokenizer
  # - name: SpacyFeaturizer
  # - name: RegexFeaturizer
  # - name: CRFEntityExtractor
  # - name: EntitySynonymMapper
  # - name: SklearnIntentClassifier
  # - name: intent_classifier_tensorflow_embedding
  # - name: DIETClassifier
  #   epochs: 200
    # constrain_similarities: True
    # model_confidence: linear_norm
  # - name: EntitySynonymMapper
  # - name: ResponseSelector
  #   epochs: 200
    # constrain_similarities: True
    # model_confidence: linear_norm
  # - name: FallbackClassifier
  #   threshold: 0.7
    # ambiguity_threshold: 0.1

policies:
  - name: AugmentedMemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    # constrain_similarities: True
    # model_confidence: linear_norm
    max_history: 6
    epochs: 200
  # - name: FallbackPolicy
  #   nlu_threshold: 0.6
  #   core_threhold: 0.6
  #   fallback_action_name: "action_default_fallback"
  #   enable_fallback_prediction: True
 







### suggestions form Cedric
 # install huggingface and try languagemodelfeaturizer
 # check what featurizer works with the clasifier
 # try SVM as classifier
 
 
 
 
 