### ConveRT ###
language: en

pipeline: 
  - name: ConveRTTokenizer
    "intent_tokenization_flag": False
    "intent_split_symbol": " "
    "token_pattern": None
    "model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
  - name: ConveRTFeaturizer
    "model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: True
    model_confidence: linear_norm
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
    constrain_similarities: True
    model_confidence: linear_norm
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    constrain_similarities: True
    model_confidence: linear_norm
    max_history: 5
    epochs: 100



