###  Bert + ConveRT ####
language: en

pipeline:
  - name: HFTransformersNLP
    model_name: "bert"
    model_weights: "bert-base-uncased" 
  - name: LanguageModelTokenizer
  - name: RegexFeaturizer
  - name: LanguageModelFeaturizer
  - name: ConveRTFeaturizer
    "model_url": https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
  - name: CRFEntityExtractor
  - name: DIETClassifier
    # constrain_similarities: True
    # model_confidence: linear_norm
    epochs: 200
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
    # constrain_similarities: True
    # model_confidence: linear_norm
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
    
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    # constrain_similarities: True
    # model_confidence: linear_norm
    max_history: 5
    epochs: 100

