### default ####
language: en

pipeline:
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: CRFEntityExtractor
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
     # analyzer: "word"
     # OOV_token: oov
   - name: CountVectorsFeaturizer
     # analyzer: "word"
     # OOV_token: oov
     analyzer: "char_wb"
     min_ngram: 1
     max_ngram: 4
   - name: EntitySynonymMapper
   - name: DIETClassifier
     epochs: 200
     constrain_similarities: True
     model_confidence: linear_norm
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 200
     constrain_similarities: True
     model_confidence: linear_norm
   - name: FallbackClassifier
     threshold: 0.7
     ambiguity_threshold: 0.1
   
   
policies:
  - name: AugmentedMemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    constrain_similarities: True
    model_confidence: linear_norm
    max_history: 6
    epochs: 200
